import pyb


def print_help(s):
    s.write(b"+------------------------------------------------------------------------------+\r\n")
    s.write(b"| ME 405 Romi Tuning Interface                                                 |\r\n")
    s.write(b"+---+--------------------------------------------------------------------------+\r\n")
    s.write(b"| h | Help menu                                                                |\r\n")
    s.write(b"| k | Enter wheel gains (Kp, Ki)                                               |\r\n")
    s.write(b"| s | Set V_nom (forward speed setpoint)                                       |\r\n")
    s.write(b"| o | Enter line-follow gains (Kp_line, Ki_line)                               |\r\n")
    s.write(b"+---+--------------------------------------------------------------------------+\r\n")
    s.write(b"| c | Arm calibration (w=white, b=black, a=cancel)                             |\r\n")
    s.write(b"| n | Run motors and stream encoder/tune/script data                           |\r\n")
    s.write(b"| x | Stop motors (also stops stream)                                          |\r\n")
    s.write(b"| p | Print condensed status                                                   |\r\n")
    s.write(b"| f | Toggle line follow enable                                                |\r\n")
    s.write(b"+---+--------------------------------------------------------------------------+\r\n")
    s.write(b"| i | Toggle IMU enable                                                        |\r\n")
    s.write(b"| m | Toggle IMU fusion mode (IMUPLUS <-> NDOF)                                |\r\n")
    s.write(b"| z | Zero IMU heading                                                         |\r\n")
    s.write(b"| u | Save IMU calibration profile                                             |\r\n")
    s.write(b"+------------------------------------------------------------------------------+\r\n")
    s.write(b"\r\n>: ")
    pyb.delay(10)
