import pyb

def print_help(s):
    s.write(b"+------------------------------------------------------------------------------+\r\n")
    s.write(b"| ME 405 Romi Tuning Interface (Lab 0x05)                                      |\r\n")
    s.write(b"+---+--------------------------------------------------------------------------+\r\n")
    s.write(b"| h | Help menu                                                                |\r\n")
    s.write(b"| k | Enter wheel gains (Kp, Ki)                                               |\r\n")
    s.write(b"| s | Set V_nom (forward speed setpoint)                                       |\r\n")
    s.write(b"| g | Data Collection UI                                                       |\r\n")
    s.write(b"+------------------------------------------------------------------------------+\r\n")
    s.write(b"| n | Run motors (line-follow + stream to PC)                                  |\r\n")
    s.write(b"| x | Stop motors (also stops stream)                                          |\r\n")
    s.write(b"| f | Toggle line follow enable                                                |\r\n")
    s.write(b"| o | Enter line-follow gains (Kp_line, Ki_line)                               |\r\n")
    s.write(b"| c | Arm calibration (w=white, b=black, a=cancel)                             |\r\n")
    s.write(b"+------------------------------------------------------------------------------+\r\n")
    s.write(b"| p | Print line + IMU status (err, dv, follow, heading, yawrate, calib)       |\r\n")
    s.write(b"| q | Stream line + IMU status for 3 seconds                                   |\r\n")
    s.write(b"| i | Toggle IMU enable (imu_en)                                               |\r\n")
    s.write(b"| m | Toggle IMU fusion mode (IMUPLUS <-> NDOF)                                |\r\n")
    s.write(b"| z | Zero IMU heading (sets current heading to 0)                             |\r\n")
    s.write(b"| u | Save IMU calibration profile to bno055_calib.bin                         |\r\n")
    s.write(b"+---+--------------------------------------------------------------------------+\r\n")
    s.write(b"\r\n>: ")
    pyb.delay(10)