import pyb

def print_help(s):
    s.write(b"+-----------------------------------------------+\r\n")
    s.write(b"| ME 405 Romi Tuning Interface                  |\r\n")
    s.write(b"+----+------------------------------------------+\r\n")
    s.write(b"| h  | help                                     |\r\n")
    s.write(b"| k  | set wheel Kp,Ki                          |\r\n")
    s.write(b"| s  | set V_nom                                |\r\n")
    s.write(b"| o  | set line Kp_line,Ki_line                 |\r\n")
    s.write(b"+----+------------------------------------------+\r\n")
    s.write(b"| n  | run motors + stream (for step_collector) |\r\n")
    s.write(b"| x  | stop motors/stream                       |\r\n")
    s.write(b"| f  | toggle follow_en                         |\r\n")
    s.write(b"+----+------------------------------------------+\r\n")
    s.write(b"| p  | print line+imu status                    |\r\n")
    s.write(b"| q  | stream line+imu (3s)                     |\r\n")
    s.write(b"| e  | print estimator                          |\r\n")
    s.write(b"| r  | stream estimator (3s)                    |\r\n")
    s.write(b"+----+------------------------------------------+\r\n")
    s.write(b"| i  | toggle imu_en                            |\r\n")
    s.write(b"| m  | toggle imu_mode (0x08<->0x0C)            |\r\n")
    s.write(b"| z  | zero IMU heading                         |\r\n")
    s.write(b"| u  | save IMU calib                           |\r\n")
    s.write(b"+----+------------------------------------------+\r\n")
    s.write(b"| c  | arm line sensor cal (w/b/a)              |\r\n")
    s.write(b"+-----------------------------------------------+\r\n\r\n>: ")
    pyb.delay(10)
